#--------------------#
# Jekyll config file #
#--------------------#

# Site settings
title: micah ilbery
author: Micah Ilbery
email: micah.ilbery@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website and portfolio of Micah Ilbery.
baseurl: ""
url: "https://micahilbery.com"
src_url: "https://github.com/micahilbery/micahilbery.github.io"
allow_bug_reports: true
copyright_date: 2018

#Theme Colors
theme_color: "#2f3033"
safari_pinned_tab: "#e03c9e"
ms_tile_color: "#e03c9e"

# Work Availability
available_for_hire: true
wanted_positions: "full-time positions"
wanted_locations: "either remote or located in the St. Louis / Metro-East areas"

# Collections
collections:
  work:
    output: true

# Socialmedia usernames
codepen_username: micahilbery
dribbble_username: micahilbery
github_username: micahilbery
gitlab_username: micahilbery
mastodon:
- username: micahilbery
  instance: mastodon.social
twitter_username: micahilbery

rss: rss

# Disqus for comments
disqus:
  shortname: micahilbery

# Payment usernames
paypal_username: micahilbery

# Build settings
show_hooks: false
markdown: kramdown
theme: minima
sass:
  style: compressed
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
  - npm-debug.log
  - .sass-cache
  - .gitignore
